# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HZNetwork-Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HZNetwork-Example

  pod 'HZNetwork', :path => '../'

  pod 'YYModel'
  
  pod 'YYCache'

  pod 'HZFoundation', :git=>'https://github.com/GeniusBrother/HZFoundation'

  pod 'MJRefresh', '~>3.1.12'
  
  pod 'SDWebImage'
  
  pod 'TTTAttributedLabel', '~> 2.0.0'
  
  pod 'Masonry'
end
